zigpy/bellows

bellows/uart.py

I change the debug print to show te hex bytes instead of the string.

Change debug print to hex

---

bellows/cli/util.py
bellows/commands.py
bellows/ezsp.py
bellows/types/named.py
bellows/zigbee/application.py
tests/test_ezsp.py

I have added support for the new EZSP version 5 protocol.

Added support for ezsp version 5

---

bellows/cli/opts.py

Don't force EZSP_DEVICE to be a path

---

bellows/zigbee/application.py

Removes a duplicate call to set CONFIG_SUPPORTED_NETWORKS

Remove duplicate config call

---

bellows/zigbee/zcl/__init__.py
tests/test_zcl.py

Fix read_attributes handling default response

---

bellows/cli/main.py
setup.py

Update to click_log 0.2.0

---

setup.py

* Fix leave/remove semantics (d846ca25)
* Support ZigBee 3.0 join with key (2b81609d @AndreasBomholtz)
* Support custom baud rate (b816d6d8 @AndreasBomholtz)

0.3.5 -> 0.4.0

---

bellows/cli/util.py
bellows/types/basic.py
bellows/uart.py
bellows/zigbee/appdb.py
bellows/zigbee/endpoint.py
tests/test_zigbee_util.py
tox.ini

Updated tox to use the same version of flake as Travis.

Using new flake8 and fixed errors

---

bellows/zigbee/zdo/__init__.py
tests/test_zdo.py

I saw that we got a unhandled ZDO command.

Handle permit join duration reply

---

bellows/zigbee/zcl/__init__.py
tests/test_zcl.py

Make sure that the reply to a read attribute command is a "ReadAttributeRecord"

Reply with ReadAttributeRecord

---

bellows/zigbee/zcl/__init__.py
bellows/zigbee/zcl/clusters/general.py
tests/test_zcl_clusters.py

Add support for time cluster

---

bellows/cli/application.py
bellows/ezsp.py
bellows/uart.py
bellows/zigbee/application.py

This is my attempt to fix #98. What do you say @jonatanolofsson ?

Using names types instead of numbers

---

bellows/cli/application.py
bellows/cli/opts.py

This will add manufacturer support when zigpy has that feature.

Added manufacturer support in cli

---

bellows/zigbee/application.py
tests/test_application.py

Use timeout when awaiting for a `messageSent` callback. Targeted as a partial fix for #124 
Please merge PR #147 1st and I'll rebase this one.

Wrap send_fut in a timeout

---

bellows/zigbee/application.py
tests/test_application.py

Limiting the number of concurrent requests will reduces chances of hitting MAX_MESSAGE_LIMIT_REACHED exception.

Limit the number of concurrent requests.

---

setup.py
tox.ini

Temporarily update dependencies.

Update zigpy dependencies

---

bellows/commands.py

Update incomingRouteHandler command schema.
Update setSourceRoute command schema.

Update COMMANDS schema.

---

bellows/ezsp.py
bellows/zigbee/application.py

- Debug log hexlified EZSP frame data
- Debug log deserialized EZSP frame data
- Debug log outgoing request frames

Additional debug logging.

---

bellows/zigbee/application.py
setup.py

Update EZSPCoordinator custom device class signature.

Update EZSPCoordinator signature.

---

bellows/__init__.py
bellows/zigbee/application.py
setup.py

0.8.2 Release.

---

tests/test_application.py

Fix tests after https://github.com/zigpy/zigpy/pull/192

Fix tests.

---

bellows/__init__.py
bellows/zigbee/application.py
tests/test_application.py

0.9.1 Release.

---

bellows/zigbee/application.py
setup.py
tests/test_application.py

This PR tracks change to zigpy in https://github.com/zigpy/zigpy/pull/223

Handle request/replies in Zigpy

---

bellows/zigbee/application.py
setup.py
tests/test_application.py

Sync up with zigpy https://github.com/zigpy/zigpy/pull/225, https://github.com/zigpy/zigpy/pull/226, https://github.com/zigpy/zigpy/pull/227

Sync to zigpy changes.

---

bellows/__init__.py
bellows/zigbee/application.py
setup.py
tests/test_application.py

Merge experimental branch back to dev.

Merge experimental branch back to dev.

---

README.md

Update README.md with hardware list and links

Update README.md with hardware list and links

---

.travis.yml
bellows/zigbee/application.py
tests/test_application.py
tox.ini

Drop Python 3.5 support.

---

bellows/zigbee/application.py
tests/test_application.py

Add support for group multicast requests.

Support multicast requests.

---

.github/release-drafter.yml
.github/workflows/release-management.yml

Adopt https://github.com/apps/release-drafter/ relase drafter.

Add release management.

---

bellows/__init__.py
bellows/zigbee/application.py

Allow establishing of TC link keys

---

bellows/__init__.py
bellows/zigbee/application.py

0.13.0 Release.

---

bellows/zigbee/application.py

Configure KEY_NUMBER parameter depending on EmberZNet protocol version.

Set number of link keys depending on version

---

bellows/zigbee/application.py

Fixes https://github.com/home-assistant/home-assistant/issues/31539

Hardcode link key table size

---

bellows/__init__.py
bellows/zigbee/application.py

0.13.2 Release

---

bellows/__init__.py
bellows/zigbee/application.py
tests/test_application.py

0.14.0 Release

---

.pre-commit-config.yaml
.travis.yml
bellows/cli/__init__.py
bellows/cli/application.py
bellows/cli/ncp.py
bellows/cli/network.py
bellows/cli/util.py
bellows/ezsp.py
bellows/thread.py
bellows/types/named.py
bellows/types/struct.py
bellows/uart.py
setup.py
tests/test_ezsp.py
tests/test_multicast.py
tests/test_thread.py
tests/test_uart.py
tox.ini

Add isort to checks and pre-commit.

Add isort to checks and pre-commit.

---

.github/workflows/publish-to-pypi.yml
.pre-commit-config.yaml
.travis.yml
bellows/__init__.py
bellows/cli/__init__.py
bellows/cli/application.py
bellows/cli/ncp.py
bellows/cli/network.py
bellows/cli/util.py
bellows/exception.py
bellows/ezsp.py
bellows/thread.py
bellows/types/named.py
bellows/types/struct.py
bellows/uart.py
bellows/zigbee/application.py
setup.py
tests/test_ezsp.py
tests/test_multicast.py
tests/test_thread.py
tests/test_uart.py
tox.ini

0.15.0 Release

---

bellows/__init__.py
bellows/ezsp.py
tests/test_ezsp.py

0.15.1 Release

---

bellows/__init__.py
bellows/ezsp.py

0.15.2 Release

---

bellows/cli/application.py

Cleanup CLI exceptions

---

bellows/ezsp.py
tests/test_ezsp.py

Run probe's config through device schema validation.

Run probe's config through device schema validation

---

README.md

Update README.md with more links to reference documentation

Update README.md with more links to reference documentation

---

bellows/zigbee/application.py
tests/test_application.py

Add probe() method to ControllerApplication class

Add probe() method to ControllerApplication class

---

bellows/types/named.py
bellows/types/struct.py
bellows/zigbee/application.py
bellows/zigbee/util.py

Make `EmberKeyData` just a fixed list. There's no point of having key as a `t.Struct`.

Refactor EmberKeyData

---

bellows/zigbee/application.py
bellows/zigbee/util.py
setup.py

Form network based on information in `config` dict with defaults  provided by SCHEMA_NETWORK.

Refactor form_network() method.

---

README.md

Update README.md with port configuration hints and suggestions. Baud rate suggestion copied from https://github.com/zsmartsystems/com.zsmartsystems.zigbee so credits go to @cdjackson

Update README.md with port configuration hints and suggestions

---

bellows/cli/application.py
bellows/cli/opts.py
bellows/cli/util.py

Fix CLI form command.
Allow specification of the network key.

Fix CLI form command

---

bellows/cli/application.py
bellows/cli/opts.py
bellows/zigbee/util.py
setup.py

Use network key sequence number from config.

Use network key sequence number from config

---

README.md
bellows/__init__.py
bellows/config/ezsp.py
bellows/multicast.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_multicast.py

0.16.2 Release

---

bellows/zigbee/application.py
tests/test_application.py

After HA Core restart, there's a traffic burst which may cause some `sendUnicast()` to fail with `MAX_MESSAGE_LIMIT` error status. Retry those unicasts up to three times.

Retry sendUnicast() on MAX_MESSAGE_LIMIT_REACHED errors

---

bellows/__init__.py
bellows/config/ezsp.py
bellows/zigbee/application.py
tests/test_application.py

0.17.0 Release

---

bellows/__init__.py
bellows/config/ezsp.py
bellows/ezsp.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_ezsp.py
tox.ini

0.18.0 Release

---

bellows/types/basic.py
bellows/types/named.py
bellows/zigbee/application.py
tests/test_types.py

Add `bitmap8` and `bitmap16` types. Use bitmaps for `EmberApsOption` and `EmberZdoConfigurationFlags` types.

Add bitmap types.

---

bellows/types/struct.py
setup.py
tests/test_types.py
tests/test_types_struct.py

Use puddly's `zigpy.types.Struct` implementation for `EzspStruct`

Refactor EzspStruct class.

---

bellows/zigbee/application.py

Hardcode EZSP manfucturer & model for quirk representing the coordinator.

Hardcode EZSP manfucturer & model into quirk.

---

bellows/ezsp/v8/__init__.py
tests/test_ezsp_v8.py

Fix v8 framing.

---

bellows/ezsp/__init__.py
bellows/zigbee/application.py
tests/test_application.py

Log EmberZNet version and board information.

Log EmberZNet version

---

bellows/cli/ncp.py

Don't apply default configuration for CLI configure command.

Don't apply default configuration for CLI configure command

---

bellows/config/ezsp.py

Revert "Set CONFIG_MAX_END_DEVICE_CHILDREN default to 24"

---

bellows/__init__.py
bellows/config/ezsp.py

0.18.1 release

---

tox.ini

Bump up flake8 version

---

.pre-commit-config.yaml
bellows/cli/backup.py
bellows/types/struct.py
tox.ini

Update pre-commit and tox dependencies.

Update pre-commit and tox dependencies

---

bellows/ezsp/v4/types/named.py
bellows/ezsp/v5/types/named.py
bellows/ezsp/v6/types/named.py
bellows/ezsp/v7/types/named.py
bellows/ezsp/v8/types/named.py
bellows/types/basic.py
bellows/types/named.py
setup.cfg
tests/test_types.py

Implement `undefined` members for undefined enum values.

Refactor Enum "named" classes

---

bellows/ezsp/v4/config.py
bellows/ezsp/v7/config.py
bellows/ezsp/v8/config.py

Revert max children back to 32.

Revert max children back to 32

---

bellows/ezsp/v8/config.py

Set joining with well known key timeout to 90s

Set joining with well known key timeout to 90s

---

bellows/ezsp/__init__.py
bellows/zigbee/application.py

Not having relays nodes is not a fatal error. Relax logging.

Not having relays nodes is not a fatal error

---

bellows/cli/ncp.py
bellows/ezsp/__init__.py
bellows/zigbee/application.py
tests/test_application.py

Include board information in CLI info command

Include board information in CLI info command

---

bellows/ezsp/__init__.py
bellows/zigbee/application.py
bellows/zigbee/util.py
tests/test_ezsp.py

Use hashed TC link keys for EZSP v5 and later.

Use hashed TC link keys for EZSP v5 and later

---

bellows/zigbee/application.py
tests/test_application.py

Print network parameters during startup

Print network parameters during startup

---

README.md

Update README.md to mention EFR32 "Mighty Gecko" as well as the new EZSP v4/v5/v6/v7/v8 support.

Update README.md to mention EFR32 and EZSP v4/v5/v6/v7/v8 support

---

.pre-commit-config.yaml
bellows/cli/backup.py
bellows/ezsp/v4/commands.py
bellows/ezsp/v5/commands.py
bellows/ezsp/v6/commands.py
bellows/ezsp/v6/types/named.py
bellows/ezsp/v7/commands.py
bellows/ezsp/v7/types/named.py
bellows/ezsp/v7/types/struct.py
bellows/ezsp/v8/__init__.py
bellows/ezsp/v8/commands.py
bellows/ezsp/v8/types/named.py
bellows/ezsp/v8/types/struct.py
bellows/thread.py
bellows/zigbee/application.py
tox.ini

Bump up black version to `20.8b1`

Adopt black==20.8b1

---

bellows/cli/ncp.py

Print board info when entering the bootloader mode.

Print board info when entering the bootloader mode

---

bellows/ezsp/__init__.py
bellows/ezsp/protocol.py
bellows/ezsp/v4/__init__.py
tests/test_ezsp.py
tests/test_ezsp_protocol.py
tests/test_ezsp_v4.py

Change MTORR intervals. Schedule MTORRs in EZSP v8

Refactor source routing setup

---

bellows/__init__.py
bellows/zigbee/application.py

0.21.1 Release

---

bellows/__init__.py
bellows/ezsp/v5/__init__.py
bellows/ezsp/v7/config.py
bellows/ezsp/v8/__init__.py
bellows/ezsp/v8/config.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_ezsp_v5.py
tests/test_ezsp_v8.py

0.20.2 Release

---

tests/__init__.py
tests/async_mock.py
tests/test_application.py
tests/test_ezsp.py
tests/test_ezsp_protocol.py
tests/test_ezsp_v4.py
tests/test_ezsp_v5.py
tests/test_ezsp_v6.py
tests/test_ezsp_v7.py
tests/test_ezsp_v8.py
tests/test_multicast.py
tests/test_thread.py
tests/test_uart.py

Use async_mock helper to transition to AsyncMock testing.

Use async_mock helper to transition to AsyncMock testing

---

bellows/zigbee/application.py
tests/test_application.py

For EZSP v8, update decision bitmask when joining with an install code.

Update decision bitmask when using install code to join

---

.travis.yml

Switch travis dist to bionic. Build on Python 3.8.6

Switch travis dist to bionic

---

README.md

Update README.md with initial backup and restore instructions as implemented by @Adminiuga in PR https://github.com/zigpy/bellows/pull/295

Update README.md with initial backup and restore instructions

---

.github/workflows/ci.yml
.github/workflows/matchers/flake8.json
.github/workflows/matchers/python.json
.pre-commit-config.yaml
README.md
bellows/cli/application.py
bellows/cli/util.py
bellows/ezsp/v7/types/named.py
bellows/ezsp/v8/types/named.py
requirements_test.txt
setup.py
tests/test_application.py
tests/test_ezsp.py
tests/test_types.py
tox.ini

Migrate bellows CI/CD to GitHub Actions.

Migrate bellows CI/CD to GitHub Actions

---

.github/workflows/ci.yml
.github/workflows/matchers/flake8.json
.github/workflows/matchers/python.json
.github/workflows/release-management.yml
.pre-commit-config.yaml
.travis.yml
README.md
bellows/__init__.py
bellows/cli/application.py
bellows/cli/backup.py
bellows/cli/network.py
bellows/cli/util.py
bellows/ezsp/__init__.py
bellows/ezsp/protocol.py
bellows/ezsp/v7/types/named.py
bellows/ezsp/v8/types/named.py
bellows/zigbee/application.py
requirements_test.txt
setup.py
tests/test_application.py
tests/test_ezsp.py
tests/test_ezsp_protocol.py
tests/test_types.py
tox.ini

0.21.0 Release

---

bellows/zigbee/application.py

Clear EZSP Counters on a regular interval to avoid counter roll-over. 
Counters are cleared every 180 * WATCHDOG_WAKE_PERIOD = 1800s

Clear EZSP Counters on a regular interval

---

bellows/zigbee/application.py

These two methods are nearly identical and can be collapsed into one.

Collapse _handle_frame_sent() / _handle_frame_failure() methods into one

---

.github/workflows/ci.yml
.github/workflows/matchers/codespell.json

Add codespell to CI

---

README.md

Update README.md with warning about Zigbee to WiFi bridges

Update README.md with warning about Zigbee to WiFi bridges

---

.github/workflows/publish-to-pypi.yml

Update pypi package publishing GH Acitons

Update workflow actions for package publishing

---

README.md

Adding IKEA Billy EZSP and Tuya TYGWZ01 plus Zigpy Wiki

Update README.md Adding IKEA Billy EZSP and Tuya TYGWZ01 plus Zigpy Wiki

---

.github/workflows/ci.yml
.github/workflows/matchers/codespell.json
.github/workflows/publish-to-pypi.yml
README.md
bellows/__init__.py
bellows/cli/network.py
bellows/ezsp/v8/config.py
bellows/zigbee/application.py
setup.py

0.22.0 Release

---

bellows/cli/main.py
bellows/cli/opts.py
bellows/cli/util.py
bellows/config/__init__.py
bellows/uart.py
tests/test_uart.py

Support for hardware flow control

Support for hardware flow control config

---

bellows/__init__.py
bellows/cli/main.py
bellows/cli/network.py
bellows/cli/opts.py
bellows/cli/util.py
bellows/config/__init__.py
bellows/uart.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_uart.py

0.23.0 Release

---

bellows/uart.py

Use correct options for software flow control

Use correct options for software flow control

---

bellows/__init__.py
bellows/uart.py

0.23.1 Release

---

bellows/ezsp/protocol.py
tests/test_ezsp_protocol.py

Log buffer allocations during EZSP initialization

Log buffer allocations during EZSP initialization

---

bellows/cli/backup.py

When restoring a coordinator backup, assume the hashed link key flag is being used, if the TC_LINK_KEY is not a well known `b"ZigBeeAlliance09"` key.

Restore hashed link keys correctly

---

.github/workflows/ci.yml
README.md
bellows/__init__.py
bellows/cli/backup.py
bellows/ezsp/protocol.py
tests/test_ezsp_protocol.py

0.24.0 Release

---

.github/workflows/ci.yml
bellows/__init__.py
bellows/zigbee/application.py
setup.py
tests/test_application.py

0.25.0 Release

---

README.md

Update README.md list of compatible hardware

Update README.md list of compatible hardware

---

.github/workflows/publish-to-pypi.yml
README.md
bellows/__init__.py
bellows/cli/dump.py
bellows/ezsp/__init__.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_ezsp.py

0.26.0 Release

---

bellows/__init__.py
bellows/types/named.py
bellows/types/struct.py
bellows/zigbee/application.py
setup.py
tests/test_application.py
tests/test_types.py

0.28.0 Release

---

bellows/zigbee/application.py
tests/test_application.py

Set specific manufacturer id reported in node descriptor, based on the joining device IEEE address.

Set specific manufacturer ID based on the joining device IEEE address

---

bellows/__init__.py
bellows/cli/dump.py
bellows/zigbee/application.py
tests/test_application.py

0.29.0 Release

---

bellows/zigbee/application.py
tests/test_application.py

During the radio state rewrite I removed the quirk for the coordinator devices. This had the unfortunate side effect ignoring the database group entries for the coordinator, which are required for EZSP coordinators to properly function with certain devices (e.g. IKEA).
Fixes https://github.com/home-assistant/core/issues/75035
Fixes https://github.com/home-assistant/core/issues/74783
---
Is there still no way to subscribe to every single group ID? Perhaps we can fix this now that EmberZNet is open source?

Load group information from existing DB device

---

bellows/zigbee/application.py

Check that endpoint 1 exists instead of assuming it does

---

bellows/__init__.py
bellows/ezsp/__init__.py
bellows/zigbee/application.py
bellows/zigbee/device.py
tests/test_application.py
tests/test_application_device.py
tests/test_application_network_state.py
tests/test_ezsp.py

0.31.2 Release

---

bellows/__init__.py
bellows/ezsp/protocol.py
bellows/ezsp/v9/commands.py
bellows/ezsp/v9/types/struct.py
bellows/zigbee/application.py
tests/test_application_network_state.py
tests/test_ezsp_protocol.py

0.31.3 Release

---

bellows/__init__.py
bellows/config/__init__.py
bellows/ezsp/__init__.py
bellows/uart.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_ezsp.py

0.32.0 Release

---

bellows/__init__.py
bellows/ezsp/__init__.py
bellows/thread.py
bellows/uart.py
bellows/zigbee/application.py
setup.py
tests/test_application.py
tests/test_ezsp.py
tests/test_thread.py
tests/test_uart.py

0.33.0 Release

---

bellows/__init__.py
bellows/cli/util.py
bellows/ezsp/__init__.py
bellows/uart.py
tests/test_ezsp.py

0.33.1 Release

---

.github/workflows/ci.yml
.github/workflows/publish-to-pypi.yml
bellows/config/__init__.py
bellows/ezsp/__init__.py
bellows/thread.py
bellows/uart.py
bellows/zigbee/application.py
bellows/zigbee/device.py
setup.py
tests/test_application.py
tests/test_application_device.py
tests/test_application_network_state.py
tests/test_ezsp.py
tests/test_uart.py

https://github.com/zigpy/zigpy/pull/1043

Implement new zigpy packet api

---

.github/workflows/ci.yml
.github/workflows/publish-to-pypi.yml
bellows/__init__.py
bellows/config/__init__.py
bellows/ezsp/__init__.py
bellows/uart.py
bellows/zigbee/application.py
bellows/zigbee/device.py
setup.py
tests/test_application.py
tests/test_application_device.py
tests/test_application_network_state.py
tests/test_ezsp.py
tests/test_uart.py

0.34.0 Release

---

bellows/__init__.py
bellows/zigbee/application.py
tests/test_application.py

0.34.1 Release

---

bellows/__init__.py
bellows/zigbee/application.py
tests/test_application.py

0.34.2 Release

---

bellows/zigbee/application.py

For some reason CI did not run at all for this PR but it was still allowed to be merged.

Fix CI failures caused by #505

---

.pre-commit-config.yaml

https://github.com/PyCQA/flake8/issues/1737

Use new repository URI for flake8

---

.pre-commit-config.yaml
bellows/__init__.py
bellows/cli/dump.py
bellows/zigbee/application.py

0.34.4 Release

---

.github/workflows/ci.yml
bellows/__init__.py
bellows/types/basic.py
bellows/uart.py
bellows/zigbee/util.py
setup.py
tests/test_application.py
tests/test_uart.py
tests/test_util.py

0.34.5 Release

---

bellows/uart.py
tests/test_uart.py

Fix for https://github.com/home-assistant/core/issues/86800
This does *not* fix the underlying problem with the multi-PAN addon causing the startup connection failure, but it will prevent the connection failure from propagating an unexpected `CancelledError` from the closing UART thread event loop into the "real" event loop, effectively shutting it down.

Prevent the UART thread from propagating `CancelledError`

---

bellows/__init__.py
bellows/uart.py
bellows/zigbee/application.py
tests/test_application_network_state.py
tests/test_uart.py

0.35.7 Release

---

bellows/__init__.py
bellows/uart.py

0.34.8 Release

---

.pre-commit-config.yaml
bellows/types/named.py
tests/test_application.py
tests/test_commands.py
tests/test_multicast.py

Bump pre-commit dependencies

---

bellows/zigbee/application.py

This allows for the downstream application to send two consecutive group commands without waiting for a send confirmation for the first.

Only wait for send status confirmation for unicasts

---

bellows/zigbee/application.py
tests/test_application.py

Zigbeed occasionally interrupts the energy scan without any error message:
```Python
2023-05-02 22:34:08.447 homeassistant bellows.ezsp.protocol DEBUG Send command startScan: (<EzspNetworkScanType.ENERGY_SCAN: 0>, <Channels.ALL_CHANNELS: 134215680>, 2)
2023-05-02 22:34:08.448 homeassistant bellows.uart DEBUG Data frame: b'1212a1a9012a15322f7e'
2023-05-02 22:34:08.448 homeassistant bellows.uart DEBUG Sending: b'82503a7e'
2023-05-02 22:34:08.448 homeassistant bellows.ezsp.protocol DEBUG Application frame received setPolicy: [<EzspStatus.SUCCESS: 0>]
2023-05-02 22:34:08.449 homeassistant bellows.uart DEBUG Sending: b'227d3321a94e2a15b2a16b4d2753a27e'
2023-05-02 22:34:08.450 homeassistant bellows.uart DEBUG Data frame: b'2313a1a94e2a15b25994dc767e'
2023-05-02 22:34:08.451 homeassistant …
```

Retry energy scans until they succeed for Zigbeed

---

bellows/__init__.py
bellows/ezsp/__init__.py
bellows/zigbee/application.py
tests/test_application.py
tests/test_application_network_state.py
tests/test_ezsp.py

0.35.3 Release

---

bellows/__init__.py
bellows/ezsp/config.py
bellows/ezsp/protocol.py
tests/test_ezsp_protocol.py

0.35.4 Release
