zigpy/bellows

- bellows/uart.py
After a reset the counters needs to be reset, or else the sequence is out of order.
> Reset send_req and rec_seq when receiving a RST ACK.

- README.md
- setup.py
This is an API-breaking release. Endpoints no longer have a "clusters"
attribute, but a "in_clusters" and "out_clusters" attributes instead.
Highlights:
- EZSP 5 support (@AndreasBomholtz)
- More robust handling of RST frames (@AndreasBomholtz)
- CLI should work on Windows now
- Python 3.4.2 now works (72bc167a)
> 0.2.7 -> 0.3.0

- bellows/cli/network.py
This is a fix for the cli leave command.
I got this error when running the command:
```
error: Task was destroyed but it is pending!
error: task: <Task pending coro=<Gateway._send_task() running at /home/andreas/projects/bellows/bellows/uart.py:157> wait_for=<Future pending cb=[Task._wakeup()]>>
Exception ignored in: <generator object Gateway._send_task at 0x7f6d07b93938>
Traceback (most recent call last):
File "/home/andreas/projects/bellows/bellows/uart.py", line 157, in _send_task
File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
File …
```
> Added missing close to leave command

- bellows/zigbee/application.py
- bellows/zigbee/zcl/__init__.py
- bellows/zigbee/zdo/__init__.py
- tests/test_zcl.py
- tests/test_zdo.py
The only information needed from the APS frame is the cluster ID. This
moves towards not using any EZSP-specific structures in the zigbee code.
> Change ZDO/ZCL deserialize signature

- bellows/cli/application.py
- bellows/zigbee/appdb.py
- bellows/zigbee/application.py
- bellows/zigbee/zdo/types.py
- tests/test_appdb.py
- tests/test_application.py
It's normal for a device to leave the network and rejoin. "Leave" shouldn't
remove a device from the application (or the database).
> Make "leave" not remove device; add "remove"

- bellows/cli/util.py
When trying to connect to a device that do not exist, the exception was shown with full backtrace. Now just the error message is shown.
> Added exception handling to cli connect

- bellows/cli/opts.py
New output:
```
Usage: bellows devices [OPTIONS]
Error: Invalid value for "-D" / "--database": Path "/home/halkeye/.config/bellows/app.db" does not exist.
```
> Add error reporting when database isn't provided when needed

- bellows/zigbee/application.py
- tests/test_application.py
I was debugging a device and found that this policy has to be set to make the whole join process to finish correctly, when using install key.
> Change policy to allow generation of new TC keys

- bellows/zigbee/application.py
- bellows/zigbee/device.py
- tests/test_application.py
If a device changes ID during join we will try to talk to the new ID instead. 
I'm trying to handle the issue #44
> Handle new id in join

- setup.py
- Remove dependencies on pycrypto and crccheck (moved to zigpy)
- Don't require a specific version of zigpy
> Dependency fixes

- bellows/uart.py
- tests/test_uart.py
This should fix the issue #76. @titilambert Can you test this small change?
> Added guard before setting result on reset future

- bellows/cli/application.py
app() does the loop wrangling itself, so calling these functions async is
incorrect and makes the commands do nothing, since they resolve to
futures that are never waited on.
Fixes #128.
> Un-async CLI functions that explicitly invoke app()

- bellows/commands.py
- bellows/types/basic.py
- bellows/zigbee/application.py
- tests/test_application.py
Add endpoint containing IAS client cluster during HUSBZB initialization.
A few IAS devices, particularly [Bosch ISW-ZPR1-WP13](https://us.boschsecurity.com/en/products/intrusionalarmsystems/premiseswireless/zigbee/zigbee_products_56458) (humongous, but cheap) and [Nyce-3014-HA](https://www.amazon.com/NYCE-NCZ-3014-HA-ZigBee-Garage-Sensor/dp/B00WTDV1TU) (and Nyce is very nyce) won't stay on the network after joining, unless there's an endpoint with IAS client cluster on the controller. 
Kudos to @Yoda-x for figuring this out. For more details please follow [Support for HA version of NYCE sensors](https://github.com/Yoda-x/ha-zha-new/issues/47) issue on `zha_new`
> Add Zigbee Endpoint to coordinator.

- bellows/zigbee/application.py
- tests/test_application.py
- tox.ini
This is an accompanying PR for https://github.com/zigpy/zigpy/pull/91
Implement `zdo.broadcast()` and `ControllerApplication.broadcast()` methods
Rename `ControllerApplication.permit()` to `ControllerApplication.permit_ncp()`
> Broadcast unicast join

- bellows/uart.py
Make travis throw less warnings.
```
=============================== warnings summary ===============================
tests/test_uart.py::test_rstack_frame_received_nofut
/home/travis/build/zigpy/bellows/bellows/uart.py:138: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
LOGGER.warn("Reset future is None")
-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 96 passed, 1 warnings in 3.04 seconds =====================
```
> Don't use deprecated log methods.

- bellows/zigbee/application.py
Set Zigbee end device poll timeout to 256 minutes, consistent with Zigbee specification R21. [More details](https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.5.pdf) quote:
> End device timeout configuration has been upgraded to use the standard Zigbee R21 values. Prior
stacks used `EMBER END DEVICE POLL TIMEOUT` and `EMBER END DEVICE POLL TIMEOUT SHIFT`
to calculate a value in seconds. Now, `EMBER END DEVICE POLL TIMEOUT` is a value for the
enumeration in the R21 spec. The prior default was approximately 5 minutes. The default has been
changed to the 256 Minute default from R21. AppBuilder will automatically convert changed settings
to the new format. However if the macros were manually overridden, this will not be detected. If the
manual override causes an …
> Update EZSP end device timeouts.

- tests/test_ezsp.py
`test_receive_reply` uses `assert callback_mock.set_result.called_once_with([4, 5, 6])` and since `called_once_with()` is a non-existent method, the assertion will always be successful.
> Fix ezsp unit test.

- bellows/zigbee/application.py
- tests/test_application.py
Ensures  no leaking pending sequences
> Use context manager for sendUnicast or sendBroadcast requests

- bellows/exception.py
- bellows/ezsp.py
- bellows/uart.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_ezsp.py
- tests/test_uart.py
This is one of the fixes targeted to address #124 
1. Reset EZSP if we receive error frames
2. Reset EZSP if there're missing heartbeats (EZSP nop command) from EZSP
3. Reset EZSP if serial connection is lost
in my test it would successfully reconnect on USB stick un-plug/plug back in. I was able to reproduce the Error farme with "Maximum NAK exceeded" condition, by artificially suppressing sending ACKs to NCP and successfully recovering from it. 
With that said, I'm looking for volunteers to test drive it and additional feedback.
> Reset EZSP stack on error frames or missing heartbeats

- bellows/zigbee/application.py
1. With introduction of "system health" component in Home Assistant, users are spooked by "unexpected response" and "unexpected message send notification" log lines. Bump these to debug level. 
2. Provide extra information, like source/destination NWK, Endpoint ID and cluster ID in log and exception messages pertained to Zigbee communication.  This provides extra context, specifically for `DeliveryError` exceptions as in the noisy log it would be much easier to correlate service requests with `DeliveryError` exceptions.
> debug logging enhancements.

- bellows/zigbee/application.py
- tests/test_application.py
Tell the stack to increase timeout between retries when communicating with Zigbee end devices. 
> Tell the stack whether or not the normal interval between retransmissions of a retried unicast message should be increased
by EMBER_INDIRECT_TRANSMISSION_TIMEOUT. The interval needs to be increased when sending to a sleepy node so that the message is not retransmitted until the destination has had time to wake up and poll its parent. The stack will automatically extend the timeout: - For our own sleepy children. - When an address response is received from a parent on behalf of its child. - When an indirect transaction expiry route error is received. - When an end device announcement is received from a sleepy node"
Relies on https://github.com/zigpy/zigpy/pull/140
> Extended timeout for Zigbee End Devices.

- bellows/__init__.py
- setup.py
Requires `zigpy-homeassistant >= 0.3.3` published to PyPi and https://github.com/zigpy/bellows/pull/159
> WIP 0.7.2 -> 0.7.3

- bellows/multicast.py
- bellows/types/basic.py
- bellows/types/named.py
- bellows/zigbee/application.py
- setup.py
- tests/test_application.py
- tests/test_multicast.py
- tests/test_types.py
Subscribe EZSP radio to receive multicast IDs. This is a matching PR for https://github.com/zigpy/zigpy/pull/157
EZSP radio is added as a Zigpy device. Calling `await application_controller.get_device(nwk=0x0000).add_to_group(group_id, "group name")` would add group id and subscribe NCP to receive multicast for that specific ID
> EZSP multicast ID

- bellows/zigbee/application.py
- tests/test_application.py
By default in case of a missing NodeDescriptor, assume worst case scenario and use extended timeouts.
> Use ExtendedTimeout if NodeDescriptor is not available yet

- bellows/multicast.py
Since the list of multicast groups was not reset during initialization,
the controller would not resubscribe to multicast groups
it was a part of until the whole system was rebooted.
> Fix bug causing NCP to not resubscribe to multicast after restart

- bellows/zigbee/application.py
- tests/test_application.py
Don't extend timeout if sending a reply.
> Use extended timeout only for requests.

- bellows/zigbee/application.py
Some devices would report NWK address conflict, change their NWK and send out a ZDO Device Announcement message with the new NWK, which causes device to become unavailable, because zigpy still uses the old address.
Here's the relevant debug log:
```
2019-09-16 19:08:45 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomi
ngMessageType.INCOMING_BROADCAST: 4>, <EmberApsFrame profileId=0 clusterId=19 sourceEndpoint=0 destinationEndpoint=0 options
=8 groupId=0 sequence=110>, 255, -80, 0x6e13, 255, 255, b'\x1f\x13n\xea.\x01\x00@\x91\x0bP\x8e']
2019-09-16 19:08:45 DEBUG (MainThread) [bellows.zigbee.application] No such device 0x6e13
2019-09-16 19:08:45 DEBUG (MainThread) [bellows.ezsp] Application frame 124 (idConflictHandler) received: …
```
> handle_join() on ZDO Device Announce requests.

- bellows/zigbee/application.py
Increase the number of PAN_ID_CONFLICT_REPORT_THRESHOLD to 2 to limit the probability of a spurious PAN_ID changed because of a conflict. When this happens, most of the Xiaomi devices are falling of the network.
More information https://www.silabs.com/community/wireless/zigbee-and-thread/knowledge-base.entry.html/2012/06/29/why_is_my_networkch-l7gl
> Setting this value to 2 or 3 dramatically reduces the chances of a spurious PAN ID change
> Increase PAN_ID_CONFLICT_REPORT_THRESHOLD.

- bellows/ezsp.py
- bellows/zigbee/application.py
- tests/test_ezsp.py
Zigbee End Devices timeout is configured differently in EZSP protocol version 7 or later. Make timeout configuration protocol specific.
> End Device timeout configuration depending on version.

- tests/test_application.py
> Fix tests.

- bellows/zigbee/application.py
- tests/test_application.py
`permit_with_key()` produces
```
debug: MulticastTableEntry[15] = <EmberMulticastTableEntry multicastId=0x0000 endpoint=0 networkIndex=0>
debug: Send command addTransientLinkKey: (91:e3:5d:0b:00:6f:0d:00, [187, 253, 160, 137, 172, 42, 120, 128, 28, 247, 252, 189, 166, 83, 57, 116])
'EmberKeyData' object has no attribute 'contents'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/usr/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
t.join()
File "/usr/lib/python3.7/threading.py", line 1032, in join
self._wait_for_tstate_lock()
File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):
KeyboardInterrupt
```
This PR fixes parameter sent to `addTransientLinkKey()` command.
> Fix permit with install code.

- bellows/zigbee/application.py
- tests/test_application.py
This PR removes the EZSP join handler. All devices were triggering handle_join 2x because device announce was also triggering the join handler.
> Remove EZSP join handler

- bellows/cli/util.py
When testing "bellows form" locally, I noticed that sometimes the
command would not exit on it's own. When investigating, I noticed that
the utility shutdown() function incorrectly referred to the function app
rather than the local app created in async_inner(). The resultant
AttributeError was previously unnoticed because shutdown() silently
catches all exceptions.
This patch adds a reference to application as a local variable in the
top-level utility function, allowing close() to be called correctly.
> cli: Call EZSP.close() on cli command completion

- bellows/uart.py
- tests/test_uart.py
Don't leave thread running, if we can't open serial port.
> Close thread on UART opening failure.

- bellows/exception.py
- bellows/ezsp.py
- setup.py
- tests/test_ezsp.py
Implement a method allowing upper layer applications to detect whether a radio module is present on a given serial port .
Implements `bellows.ezsp.EZSP.probe(port, baudrate) -> bool` async class method, which return True if radio was detected on port path or False otherwise. All exceptions are consumed by the method.
> Add probe EZSP method.

- bellows/ezsp.py
Similar fix, looks like this got missed in refactoring.
> ezsp: fix incorrect ezsp_version reference

- bellows/ezsp.py
Prevent use of the closed loop.
> Close EZSP as soon as we loose connection

- bellows/cli/util.py
Correctly convert CLI Node parameter (ieee) into an IEEE address.
> Convert CLI node parameter correctly

- setup.py
Change module name back to original `bellows`.
> Change module name back to original bellows

- bellows/config/__init__.py
- bellows/config/ezsp.py
- bellows/zigbee/application.py
Configure EZSP (part of `startup()` method) based on Schema defaults. This would allow fine tuning of EZSP from the application itself without changes to bellows module itself.
> Configure EZSP based on EZSP schema

- bellows/multicast.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_multicast.py
Make `Multicast.initialize()` a class method.
> Refactor multicast initialization.

- bellows/cli/ncp.py
Add "bootloader" CLI command.
If NCP has bootloader available, it will launch it. For example on Nortek GoControl HUSBZB-1 sticks, after launching bootloader, it is available via terminal using `115200` baud connection rate.
```
debug: Using selector: EpollSelector
debug: Using selector: EpollSelector
debug: Connected. Resetting.
debug: Resetting EZSP
debug: Resetting ASH
debug: Sending: b'1ac038bc7e'
debug: RSTACK Version: 2 Reason: RESET_SOFTWARE frame: b'c1020b0a527e'
debug: Send command version: (4,)
debug: Sending: b'004221a850ed2c7e'
debug: Data frame: b'0142a1a8532825d4f4497e'
debug: Sending: b'8160597e'
debug: Application frame 0 (version) received: b'07023066'
debug: Send command version: (7,)
debug: Sending: b'7d31432157542a1205877e'
debug: Data frame: …
```
> Add "bootloader" CLI command

- README.md
Update README.md with new (old) link to PyPI project for bellows
> Update README.md with new (old) link to PyPI project for bellows

- bellows/cli/application.py
- bellows/cli/main.py
- bellows/ezsp.py
Fix zcl commands CLI command.
Set default logging level to warning.
Fixes #252
> Fix zcl commands CLI command

- bellows/config/ezsp.py
Remove default value for CONFIG_TRANSIENT_KEY_TIMEOUT_S. 
Fixes #255
> Remove default value for CONFIG_TRANSIENT_KEY_TIMEOUT_S

- README.md
Update README.md with more introduction descriptions about Silabs EmberZNet interfaces for new developers. My goal was is to get a better introduction to the workings of bellows & EZSP interfaces.
Much of this information been copied from Z-Smart Systems (@zsmartsystems) readme file for [com.zsmartsystems.zigbee](https://github.com/zsmartsystems/com.zsmartsystems.zigbee) by @cdjackson which by the way contains even more information which I was not sure if it should also be copied to bellows readme file as well or not, please see:
- https://github.com/zsmartsystems/com.zsmartsystems.zigbee/blob/master/README.md
Note! If you read his whole readme you see it contains more detailed introductions about everything.
The library supports the Silicon Labs EZSP (EmberZNet Serial Protocol) APIs for …
> Update README.md with more introduction descriptions about EmberZNet interfaces for new developers

- bellows/config/ezsp.py
- bellows/multicast.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_multicast.py
Proper initialize EZSP multicast table.
Allow configurable multicast table size.
Fixes https://github.com/home-assistant/core/issues/35661
> Proper initialize EZSP multicast table

- bellows/config/ezsp.py
Reduce the default max number of end devices the coordinator will support to 24. Fixes https://github.com/home-assistant/core/issues/36563
> Set CONFIG_MAX_END_DEVICE_CHILDREN default to 24

- bellows/ezsp.py
- tests/test_ezsp.py
Hi,
I added the support for EZSP v8 framing which allows bellows to run against Silicon Labs EmberZNet SDK 6.7.6 (latest). EZSP v8 simply passes Frame ID field to a 16 bit value
I added it so it does not affect currently supported devices, but adapts to those that run a newer version of EZSP
I tested it over a Silicon Labs Thunderboard Sense 2 (EFR32MG12 based), for which I built a specific NCP firmware (bellows CLI commands tests only)
Best,
Brian
> Feature efr32 support - EZSP v8 framing

- bellows/zigbee/application.py
- tests/test_application.py
If EZSP stack reports id conflict (NWK address conflict) then mark device as leaving.
If we get a trust center callback, then use that information to update NWK address of the device if it exists.
> handle ID conflict reports

- bellows/zigbee/application.py
- tests/test_application.py
There was a problem were Zigpy would have stale information, if EZSP reported NWK conflict. After further testing, the approach in #274 was causing some issues, if the user was joining a device which was reset without removing the device 1st.
In new approach, we revert to the old behavior where we trigger a `handle_join()` and let it handle all the updates and updating the saved state.
> Trigger handle_join on TC join call backs

- README.md
Update README.md to mention support for ITEAD Sonoff ZBBridge if flashed with Tasmota and EmberZNet 6.5.x.x
See https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html and https://templates.blakadder.com/sonoff_ZBBridge.html
@Adminiuga Please also see matching PRs https://github.com/zigpy/zigpy/pull/447 & https://github.com/home-assistant/home-assistant.io/pull/14124
> Update README.md to mention ITEAD Sonoff ZBBridge with Tasmota

- bellows/config/__init__.py
- bellows/ezsp/protocol.py
- bellows/ezsp/v4/__init__.py
- bellows/ezsp/v4/config.py
- bellows/ezsp/v5/__init__.py
- bellows/ezsp/v5/config.py
- bellows/ezsp/v6/__init__.py
- bellows/ezsp/v6/config.py
- bellows/ezsp/v7/__init__.py
- bellows/ezsp/v7/config.py
- bellows/ezsp/v8/__init__.py
- bellows/ezsp/v8/commands.py
- bellows/ezsp/v8/config.py
Allow configuration of the custom EZSP policies, e.g. 
```yaml
zha:
zigpy_config:
ezsp_policies:
TRUST_CENTER_POLICY: 0
TC_KEY_REQUEST_POLICY: 80
```
key -- is `EzspPolicyId`
value -- is `EzspDecisionId`
> Allow custom policy configuration.

- bellows/cli/__init__.py
- bellows/cli/backup.py
- bellows/cli/util.py
Theoretically this allows backing up and restoring NCP state between the hardware version. 
Please note this is highly experimental. The restoration doesn't restore NCP children and relies on children just to find a new parent. 
Another warning: if this is done between different hardwares, the EUI64 is going to be different on the new hardware meaning the binding tables on all the devices are going to be wrong. 
You either have to reconfigure all the devices -- recommended so the bindings are updated or alternatively you could override the EUI64 on the new hardware, essentially producing a clone. **Be very careful** if you decide to go this route. You can change the EUI64 only once and once you set it it is impossible to change it without a specialized hardware (SWD programmer).
To export …
> Export/Import NCP Trust Center parameters

- bellows/ezsp/v4/types/named.py
- bellows/ezsp/v5/types/named.py
- bellows/ezsp/v6/types/named.py
- bellows/ezsp/v7/types/named.py
- bellows/ezsp/v8/types/named.py
For erased or missing key, EZSP returns `EmberKeyType` of `0x00`. Add a type for it, so it doesn't throw a deserialization error.
> Add an enum member to represent a missing key

- bellows/cli/backup.py
Restore EUI64 prior setting the initial security state, so the partner EUI for TC key is set correctly
> Restore EUI64 prior setting the initial security state

- bellows/ezsp/__init__.py
- bellows/ezsp/protocol.py
- bellows/ezsp/v4/__init__.py
- bellows/ezsp/v8/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
Fix source routing for V7 and earlier protocols. If the route is not known, then return an awaitable.
> Return an awaitable if route is not known

- bellows/ezsp/v8/config.py
Change the default TC policy for EZSPv8 to allow unsecure rejoins.
> Change the default TC policy for EZSPv8 to allow unsecure rejoins

- bellows/cli/backup.py
Restore network update id. This is more of a hack, because EZSP doesn't expose commands to set NWK Update ID during formation.
> Set network update id after network was formed from backup.

- bellows/config/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
If we receive a frame from an unknown device, it means device is on the network, but not in `zigbee.db` and we have no knowledge of that device. In such case, try to lookup IEEE of that sender by NWK and if successful, try discovery of the device.
by default this is disabled, as it not gonna work well for sleepy Xiaomi devices, unless you keep them awake. To enable, add parameter `handle_unknown_devices` with value `yes` to zigpy configuration dict.
in case of Home assistant, add to `configuration.yaml`
```yaml
zha:
zigpy_config:
handle_unknown_devices: yes
```
> Handle discover of unkwnown devices

- bellows/ezsp/__init__.py
- bellows/ezsp/protocol.py
- bellows/ezsp/v8/__init__.py
- bellows/zigbee/application.py
The configured TRUST_CENTER_POLICY becomes the default policy applied when no joins are allowed. During the period of allowing new joins, TC policy is modified with: `EzspDecisionBitmask.ALLOW_JOINS | EzspDecisionBitmask.ALLOW_UNSECURED_REJOINS`
After joining period is expired, the configured TC policy is restored. By default it is `EzspDecisionBitmask.ALLOW_JOINS | EzspDecisionBitmask.IGNORE_UNSECURED_REJOINS`
> Allow unsecure rejoins for the duration of  Mgmt_Permit_Joining_req

- bellows/cli/backup.py
- bellows/ezsp/v4/config.py
- bellows/zigbee/application.py
- bellows/zigbee/util.py
Implement https://www.silabs.com/community/wireless/zigbee-and-thread/knowledge-base.entry.html/2018/06/18/hashed_link_keys-Ltmt
As side effect add well known TC global link key as "transient key" to allow interoperability with HA12 devices.
> Use Hashed TC link key

- tests/test_thread.py
- tox.ini
Since we're not supporting Py35 or Py36 we can drop async_generator requirement.
> Remove async_generator dependency

- bellows/ezsp/protocol.py
- tests/test_ezsp_protocol.py
With new EZSP firmware appearing every day, it is unpractical for all firmwares to have the same default values, so instead `bellows` relies on firmware vendor to have sensible defaults and setting the configuration value is a preference, not a requirement.
> Don't error out if setting a configuration value fails

- README.md
Older version of 6.5.x.x of EmberZNet is no longer needed
> Update README.md remote need for older EmberZNet as EZSP v4/v5/v6/v7/v8 is now supported

- bellows/zigbee/application.py
- tests/test_application.py
When debug logging is enabled, instead of `nop()` EZSP command, read back all EZSP counters.
> Log EZSP counters

- bellows/zigbee/application.py
> No need to close EZSP on shutdown if it wasn't opened

- bellows/ezsp/v7/config.py
- bellows/ezsp/v8/config.py
For EZSP v7 set the `CONFIG_KEY_TABLE_SIZE=12`, since EmberZNet 6.4.1 (EZSP v7) still had the default at 0. But later EmberZNet version have the default at 12, so don't set it explicitly in EZSP v8 and let firmware makers to configure the default.
> Change defaults for CONFIG_KEY_TABLE_SIZE

- bellows/ezsp/v5/__init__.py
- bellows/ezsp/v8/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_ezsp_v5.py
- tests/test_ezsp_v8.py
Add Global TC link key as a transient link key only for EZSP v5 or later.
HUSBZB-1 comes with EmberZNet 5.4.1.0 based firmware and does not support transient link key command. 
Fixes #340
> Add Global TC link key as a transient link key only for EZSP v5 or later

- README.md
Update bellows radio library for zigpy README.md with EmberZNet and EZSP Protocol Version information.
@mtx512 @grobasoz @NilsBohr @walthowd @MattWestb Does anyone of you have the expertise to confirm if all this is right?
Silicon Labs do not currently have a consolidated list of changes by EmberZNet SDK or EZSP protocol version. The EZSP additions, changes and deletions have only ever been listed in the "Zigbee EmberZNet Release Notes" (EmberZNet SDK) under the "New items" section as well as the matching UG100 EZSP Reference Guide included with each EmberZNet SDK release.
The largest change was between EZSP v4 (first added in EmberZNet 4.7.2 SDK) and EZSP v5 that was added in EmberZNet 5.9.0 SDK which requires the Legacy Frame ID 0xFF. The change from EZSP v5 to EZSP v6 was done in …
> Update README.md with EmberZNet and EZSP Protocol Version information

- README.md
Update zha.markdown with recommendations to upgrade EmberZNet NCP application firmware on Silicon Labs based Zigbee adapter and links to information about how to do so where it is available.
Looks like quite a few users in the Home Assistant community have reported that some paring issues or instability with old firmware are resolved simply by upgrading EmberZNet firmware.
Does someone, by the way, have a link to good instructions on how-to upgrade firmware on Telegesis ETRX357USB adapters as well as links to publicly available firmware images for them?
Also submit PR https://github.com/home-assistant/home-assistant.io/pull/14503 to update https://www.home-assistant.io/integrations/zha/
Upgrading firmware might not be the solution for everyone or even possible on all adapters but if at …
> Update README.md with recommendation to upgrade EmberZNet firmware

- bellows/ezsp/protocol.py
- tests/test_ezsp_protocol.py
Handle gracefully invalidCommand frames.
`invalidCommand` frame is normal part of protocol operation and can happen under certain circumstances, e.g. https://github.com/zigpy/bellows/issues/366 where some very old firmwares do not support command "readCounters".
> Handle gracefully invalidCommand frames

- bellows/zigbee/application.py
- tests/test_application.py
Don't try to `readCounters` on EZSP version 4, as some really old firmware on Telegis sticks does not support those. This would disable counter reading on HUSBZB-1 sticks as well, unless firmware is updated to a newer one. 
This 2nd part of the "counter" problem fix, indicated in https://github.com/zigpy/bellows/issues/366
> Don't log counters on EZSP version 4

- bellows/cli/backup.py
- bellows/cli/network.py
- bellows/ezsp/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_ezsp.py
Process `stackStatusHandler` frames properly when leaving the network. This speed up tests by eliminating a 1s sleep.
> Refactor leaveNetwork command

- bellows/ezsp/protocol.py
Use a more sensible EZSP command timeout value.
> Use a more sensible EZSP command timeout value

- README.md
Update README.md for bellows with a couple of links to firmware upgrade resources from @NilsBohr (Elelabs) and @walthowd
Telegesis ETRX357USB firmware upgrade to EmberZNet 6.6 tested and confirmed by @macfly92 in https://github.com/zigpy/bellows/issues/347
> Update README.md with links to firmware upgrade resources

- README.md
Added the DEFARO SprutStick Pro (based on EFR32MG12) to the list of compatible hardware in README.md for bellows.
Ships with standard EmberZNet so should work according to its hardware developer @sprut666666 as per discussion in https://github.com/zigpy/bellows/issues/242
- https://defaro.ru/index.php/product/89-controllers/257-sprutstick-pro
Originally designed to be used with Spruthub (Sprut.hub) which is a home automation platform from Russia -> @sprut
- https://spruthub.ru/stick
> Added the DEFARO SprutStick Pro list of compatible hardware in README.md

- setup.py
Don't pin old version of click-log package.
Fixes #376
> Don't pin old version of click-log package

- bellows/cli/network.py
I'm new to bellows, and I am testing it via the CLI. I noticed that `network.extendedPanId` must be used instead of `network.ExtendedPanId` for a `bellows join` command.
I still don't have any success (next error: `TypeError: zha_security() missing 1 required positional argument: 'config'`), but at least I'm one step further with this fix.
> cli: join network fails because of typo

- setup.py
Click is written lower case. At least in my setup the capital lead to
pypi to pick the wrong package:
```
Searching for Click
...
Best match: click log-0.3.2
```
> Fix click dependency name

- bellows/ezsp/v8/config.py
Increase the max for children and neighbors to support 'pro' type devices that can handle the settings. 
Remove the default for MAX_END_DEVICE_CHILDREN for V8 EZSP. Inherit the default from NCP
> Increase maximums to support 'pro' devices

- bellows/zigbee/application.py
- tests/test_application.py
Send multicast requests optimistically -- don't wait for NCP confirmation (messageSentHandler) as those sometimes are delayed.
Don't send multicast under a lock.
Limit the time the Unicast requests are sent under the lock.
> Send multicast requests optimistically

- bellows/cli/network.py
FIX CLI joining EZSP as an end device.
Fixes #401
> CLI fix for joining as an end device

- README.md
Small note that ITEAD Sonoff ZBBridge is not recommended.
* _ITead Sonoff ZBBridge (**Note! WiFi-based bridges are not recommended for ZHA with EZSP radios.** Also, this first have to be flashed with Tasmota firmware and Silabs EmberZNet NCP EZSP UART Host firmware to use as Serial-to-IP adapter)_
This pull request replaces https://github.com/zigpy/bellows/pull/406
> Small note that ITEAD Sonoff ZBBridge is not recommended

- README.md
Add Bitron Video/Smabit BV AV2010/10 USB-Stick (a.k.a. Telekom Magenta Stick) based on Silicon Labs Ember 3587.
This updates README.md for bellows as the plan is to remove all adapters from zigpy README in https://github.com/zigpy/zigpy/pull/705
> Add Bitron Video/Smabit adapter to README

- bellows/zigbee/application.py
- tests/test_application.py
https://github.com/zigpy/zigpy/pull/711
Could also keep the code compatible with both versions of zigpy by testing `device.node_desc.is_end_device in (True, None)` instead of just `device.node_desc.is_end_device`.
CI passes locally for me with zigpy `dev`.
> Handle `None` node descriptors

- README.md
one `<` was missing and port 8888 is only for Sonoff ZBB better neutral.
> Fixing socket://<adapter-IP>:<port>

- bellows/zigbee/application.py
- tests/test_application.py
Sets the following `ControllerApplication` instance properties on startup:
- `extended_pan_id`
- `pan_id`
- `channel`
- `channels`
- `nwk_update_id`
> Populate `ControllerApplication` network parameter properties on startup

- bellows/cli/dump.py
Moves a few logging messages from stdout to stderr and terminates the command when the stdout pipe is broken.
"Fixes" https://github.com/zigpy/bellows/issues/425 when used with https://github.com/zigpy/zigpy-cli/pull/1
> Allow `bellows dump` to pipe packets over stdout

- bellows/cli/dump.py
https://github.com/zigpy/zigpy-cli/pull/1#issuecomment-884638373
The FCS is validated by EmberZNet so the frames are valid, only the checksum is wrong.
> Automatically fix the frame FCS in `bellows dump`

- bellows/ezsp/__init__.py
- tests/test_application.py
- tests/test_ezsp.py
When probing for the radio, try default baudrate 1st then 115200 baudrate.
This would allow ZHA to detect EZSP based radio which are using 115200 serial port rate.
> Refactor ezsp.probe() method

- bellows/zigbee/application.py
- tests/test_application.py
Avoid setting up APS Route Discovery option, if running source routing on EZSP V8 or newer
> Don't use route discovery if source routing is enabled on EZSP v8

- bellows/zigbee/application.py
- tests/test_application.py
EZSP protocol version 8 does not allow setting the source routes from the host. This causes issues on restarts, because the NCP does not have the routes, even though zigpy still have the old routes and because of this it does not set the ROUTER_DISCOVERY APS options. 
Clear device relays (source routes) on restart and use router discovery until new route is received.
> Reset relays for EZSP version 8

- bellows/cli/dump.py
Seems like the incorrect FCS captured on EZSPv8 depends on the channel, e.g. here's channel 20
```
Frame 1: 54 bytes on wire (432 bits), 54 bytes captured (432 bits)
IEEE 802.15.4 Data, Dst: 0x0000, Src: 0xc08f, Bad FCS
Frame Control Field: 0x8841, Frame Type: Data, PAN ID Compression, Destination Addressing Mode: Short/16-bit, Frame Version: IEEE Std 802.15.4-2003, Source Addressing Mode: Short/16-bit
Sequence Number: 15
Destination PAN: 0x5812
Destination: 0x0000
Source: 0xc08f
FCS: 0x0014 (Incorrect, expected FCS=0xe726)
[Expert Info (Warning/Checksum): Bad FCS]
Data (43 bytes)
```
So this forces FCS recalculation on EZSP v8 unconditionally.
> Fix frame FCS on EZSPv8 unconditionally

- bellows/zigbee/application.py
Handle exceptions in case EZSP Radio doesn't support the getMfgToken
token command. This is required to make ZHA work with the EmberZNet
Zigbee stack running on Linux (zigbeed).
See also discussion: https://github.com/zigpy/zigpy/discussions/894
> Skip get_board_info() in case EZSP Radio doesn't support it

- bellows/config/__init__.py
Allows network configuration at initialization without calling zigpy library
> Import CONF_NWK parameters to config

- bellows/config/__init__.py
CI allowed #451 to be merged with a failing isort check
> Fix isort after merge of #451

- bellows/cli/__init__.py
- bellows/cli/stream.py
The stream subcommmand uses the manufacturing library to transmit random
characters continously. This is useful for RF testing and approvals.
> Add stream subcommand for RF testing

- bellows/ezsp/__init__.py
The Silicon Labs zigbee daemon restarts on reset. Restarts take some
time, and with a probe timeout of 2s probe often stops before the
zigbeed finished restarting. This is especially noticable since Gecko
SDK 4.0.2.0.
> Set probe timeout to 3s for zigbeed

- bellows/cli/__init__.py
- bellows/cli/tone.py
From the mfglib description:
[...] start a TX tone that can be used to measure the PA output power,
phase noise, frequency offset and spurious emissions using a spectrum
analyzer. The TX tone is a continuous unmodulated transmission.
> Add tone command for RF testing

- bellows/cli/application.py
Using bind command returns error similar to "function takes 2 attributes but 3 were given".
In Zigpy it is defined as  
`def bind(self, cluster):`
So endpoint shouldn't be there and cluster should be "clust" returned from previous function and not "cluster" as the latter is a number from the cli and not a "cluster" class object.
> Fix bind command

- bellows/ezsp/__init__.py
- tests/test_ezsp.py
When a RSTACK message is processed right after the UART has been opened,
it causes EZSP.enter_failed_state() getting called at a point where the
application callbacks are not registered yet. In that case the UART
will get closed and it won't get opened again. Bellows is stuck with a
closed transport.
Avoid this issue by not closing the port in case there is no application
callback registered yet.
Typically, it is unlikely that a RSTACK message arrives right when
the port gets opened (the race window is very narrow). However, with
hardware flow control opening the port leads to RTS signal to get
asserted which causes the radio to send pending messages, e.g. resets
caused by EmberZNet watchdog.
Note: With hardware flow control this is only the case if the tty "hupcl"
option is set. The …
> Fix UART port close on RSTACK message during startup

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- bellows/__init__.py
- bellows/cli/__init__.py
- bellows/cli/application.py
- bellows/cli/dump.py
- bellows/cli/stream.py
- bellows/cli/tone.py
- bellows/config/__init__.py
- bellows/ezsp/__init__.py
- bellows/thread.py
- bellows/types/named.py
- bellows/zigbee/application.py
- tests/test_ezsp.py
> 0.30.0 Release

- bellows/ezsp/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_application_network_state.py
- tests/test_ezsp.py
Will be used to show a checkbox for EZSP radios in the ZHA backup/restore dialog, to allow writing the radio EUI64 address.
> Include a `can_write_custom_eui64` stack-specific key in the backup

- bellows/ezsp/__init__.py
- tests/test_ezsp.py
Backups were being created with invalid metadata:
```json
"ezsp": {
"manufacturer": "Nabu Casa\u0000",
"board": "SkyBlue v0.1\u0000",
"version": "7.1.0.0 build 191",
"stack_version": 9,
"can_write_custom_eui64": false
}
```
> Handle null-terminated `MFG_` strings

- bellows/zigbee/application.py
- bellows/zigbee/device.py
- tests/test_application.py
- tests/test_application_device.py
This allows for energy scans to be performed via zigpy-cli (and soon ZHA) on all Z-Stack, EZSP, and deCONZ radios:
```
$ zigpy radio --baudrate 115200 ezsp /dev/cu.SLAB_USBtoUART energy-scan
Channel energy (mean of 1 / 5):
------------------------------------------------
+ Lower energy is better
+ Active Zigbee networks on a channel may still cause congestion
+ TX on 26 in North America may be with lower power due to regulations
+ Zigbee channels 15, 20, 25 fall between WiFi channels 1, 6, 11
+ Some Zigbee devices only join networks on channels 15, 20, and 25
+ Current channel is enclosed in [square brackets]
------------------------------------------------
-  11      33.73%  #################################
-  12      33.33%  #################################
-  13      36.08% …
```
> Implement energy scanning via the ZDO interface

- bellows/ezsp/v9/commands.py
- bellows/ezsp/v9/types/struct.py
I forgot to update `v9/commands.py` after rebasing #462
> Fix `getChildData` schema in v9 to match v7 and v8

- bellows/ezsp/protocol.py
- tests/test_ezsp_protocol.py
The Gecko SDKs seem to contain a few commands we never defined in the schemas. Currently bellows crashes, without logging enough to figure out what the command is.
> Log unknown commands

- bellows/zigbee/application.py
- tests/test_application_network_state.py
EZSP v8 seems to have `0x0000: 00:00:00:00:00:00:00:00` address table entry, in addition to the other reserved ones.
> Ignore the `0x0000`/`00:00:00:00:00:00:00:00` address table entry

- bellows/zigbee/application.py
Possible fix for https://github.com/home-assistant/core/issues/75292
I believe the new zigpy startup sequence can throw new types of errors, which bellows was not handling. This would cause the watchdog re-connect task to crash, which will prevent any future reconnects.
> Restart on any startup failure, not just timeouts and serial errors

- bellows/config/__init__.py
- bellows/ezsp/__init__.py
- bellows/uart.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_ezsp.py
Another possible fix for https://github.com/home-assistant/core/issues/75292.
With the new logging introduced in https://github.com/zigpy/bellows/pull/476, I was able to simulate the exact errors received by a user and then get bellows into a state where it stopped trying to reconnect after a couple of attempts. I believe this is caused by the serial port not being properly closed before it is re-opened in some circumstances, since I have been unable to break the reconnect/watchdog loop since.
> Explicitly close serial port after connection and startup failures

- bellows/ezsp/__init__.py
All newer adapters are using 115200 baud, not 57600 (which I believe is only used by the old HUSBZB-1?). Changing the default to 115200 will break CLI tools and require a ZHA configuration migration so this is a slightly more gradual change.
> Probe with 115200 baud first

- bellows/uart.py
- bellows/zigbee/application.py
- setup.py
- tests/test_application.py
- tests/test_uart.py
`startup` internally called `disconnect` in the event of a failure *after* connect but *during* initialization. `disconnect` cancels the reconnect task.
This can be replicated by yanking out a USB coordinator once to get bellows to start reconnecting, and then yanking it out halfway through startup. This problem does not really affect USB coordinators though: if their serial port is present, they probably will work. Only networked coordinators really end up in a situation where the TCP connection succeeds but the port is unusable.
https://github.com/home-assistant/core/issues/75292
> Properly handle failures after connect, during startup

- bellows/thread.py
- tests/test_thread.py
If a proxied future is cancelled by a thread shutdown, the cancellation may not have time to propagate to the outer event loop. This will stall the outer `await`.
> Fix thread shutdown proxied future race condition

- bellows/cli/util.py
- bellows/ezsp/__init__.py
- tests/test_ezsp.py
The EZSP "running" flag was not set during probing after #485 and this was not caught by unit tests. This fixes both problems.
> Fix radio probing broken by #485

- bellows/cli/util.py
- bellows/ezsp/__init__.py
- bellows/uart.py
- tests/test_ezsp.py
Add tcp:// protocol to talk to EZSP radio via TCP/IP. Compared to the
existing socket:// protocol this uses Python's loop.create_connection()
instead of pyserial. In tests this makes `bellows info` to complete
about 50x faster (measured after reset, from 0.6s to 0.012s).
> Add support for tcp protocol

- bellows/zigbee/application.py
- tests/test_application.py
#494 contained a bug where the request concurrency was enforced only for the sending stage, not for the response notification stage.
> Use the correct indentation level for the concurrency manager

- bellows/zigbee/application.py
- tests/test_application.py
Broadcasts seem to periodically fail with delivery failure statuses.
https://github.com/home-assistant/core/issues/79832
> Ignore delivery failures for broadcasts

- bellows/zigbee/application.py
To prevent send_packet to always set APS_OPTION_RETRY check if packet tx_options requires or not ACK. Addressing #504
> make ACK dependents on packet.tx_options

- bellows/config/__init__.py
- bellows/ezsp/__init__.py
Not all environments support or need threading, namely https://pyscript.net/ and command line applications:
```yaml
zha:
zigpy_config:
use_thread: false
```
Once some hard-to-reproduce, low-level bugs are ironed out of the bellows asyncio thread, I think it would be beneficial to move it into zigpy.
> Allow disabling the bellows UART thread

- bellows/cli/dump.py
Recalculate FCS for EZSP version 8, 9 or newer when capturing ZigBee traffic.
> Recalculate bad FCS for protocol versions 8 or newer

- bellows/zigbee/application.py
This PR reorganizes the context managers in send_packet so that we don't stack up a bunch of TSN's that we can't use. Now we won't create a request / reserve a TSN until we are unblocked by the concurrency managing semaphore. 
This should correct floods of duplicate TSN messages during restarts for large networks.
> Reorganize context managers in send_packet

- bellows/uart.py
- tests/test_uart.py
`protocol.eof_received()` is called when the other side closes the connection. It implicitly calls `protocol.connection_lost(None)`, which breaks reconnection logic.
> Treat TCP disconnects as lost connections

- bellows/zigbee/application.py
- tests/test_application_network_state.py
`ControllerApplication.reset_network_info` does not actually leave the current network if one isn't currently active.
> Ensure the network is running in `reset_network_info`

- bellows/uart.py
https://github.com/zigpy/bellows/pull/524 fails to apply when the connection is gracefully closed by the server and `exc=None`.
Related: https://github.com/home-assistant/core/issues/86800
> Handle startup reset exception being `None`

- bellows/zigbee/application.py
Using `CONFIG_APS_UNICAST_MESSAGE_COUNT` as the concurrency limit seems like it can cause problems when the value is large (e.g. multi-PAN defaults to 64). Instead, it will default to 8.
To increase the concurrency limit, update the zigpy configuration:
```yaml
zha:
zigpy_config:
max_concurrent_requests: ...
```
> Use global zigpy unicast concurrency limit

- bellows/ezsp/__init__.py
Otherwise, the callback will be called repeatedly with other `stackStatusHandler` events and raise invalid state exceptions.
> Clean up `formNetwork` callback after running

- bellows/zigbee/application.py
- bellows/zigbee/util.py
- tests/test_util.py
The units of the 0-255 value for energy scans is just "energy", not LQI. This is just an internal rename.
> Internally rename LQI to Energy for energy scanning

- bellows/uart.py
That way, zigpy can catch the error with https://github.com/zigpy/zigpy/pull/1188 and treat it as transient.
> Use `ConnectionResetError` instead of `OSError` when connection is reset during startup

- bellows/zigbee/application.py
- tests/test_application.py
This ensures that the network will not be re-formed unnecessarily. I haven't yet figured out what the specific status code is, but it will now be logged.
> Only throw `NetworkNotFormed` when initialization fails with `EmberStatus.NOT_JOINED`

- bellows/ezsp/__init__.py
- bellows/ezsp/protocol.py
- bellows/uart.py
- bellows/zigbee/application.py
- setup.py
- tests/test_application.py
- tests/test_ezsp.py
- tests/test_ezsp_protocol.py
- tests/test_thread.py
See https://github.com/zigpy/zigpy/pull/1187.
This has the side effect of making `ezsp.Protocol.command` an async function instead of a sync function returning a future.
> Replace `asyncio.wait_for` with `asyncio.timeout`

- bellows/ezsp/__init__.py
- bellows/zigbee/application.py
- tests/test_application.py
- tests/test_application_network_state.py
- tests/test_ezsp.py
Looks like #553 affected more than just zigbeed, as I've been able to replicate it on EmberZNet 6.9 and 7.1 with NCP USB coordinators...
The root cause appears to be us not properly waiting for stack events to happen (i.e. `NETWORK_UP` and `NETWORK_DOWN`), leading to race conditions or outright failures at random.
> Wait for explicit stack messages for network state

- bellows/ezsp/config.py
- bellows/ezsp/protocol.py
- tests/test_ezsp_protocol.py
#550 introduced a major regression for older coordinators. Below are the previous EZSP configurations:
```python
v4 set CONFIG_ADDRESS_TABLE_SIZE = 16
v4 set CONFIG_APPLICATION_ZDO_FLAGS = 3
v4 set CONFIG_END_DEVICE_POLL_TIMEOUT = 60
v4 set CONFIG_END_DEVICE_POLL_TIMEOUT_SHIFT = 8
v4 set CONFIG_INDIRECT_TRANSMISSION_TIMEOUT = 7680
v4 set CONFIG_KEY_TABLE_SIZE = 4
v4 set CONFIG_MAX_END_DEVICE_CHILDREN = 32
v4 set CONFIG_MULTICAST_TABLE_SIZE = 16
v4 set CONFIG_PACKET_BUFFER_COUNT = 255
v4 set CONFIG_PAN_ID_CONFLICT_REPORT_THRESHOLD = 2
v4 set CONFIG_SECURITY_LEVEL = 5
v4 set CONFIG_SOURCE_ROUTE_TABLE_SIZE = 16
v4 set CONFIG_STACK_PROFILE = 2
v4 set CONFIG_SUPPORTED_NETWORKS = 1
v4 set CONFIG_TRUST_CENTER_ADDRESS_CACHE_SIZE = 2
v7 changed CONFIG_END_DEVICE_POLL_TIMEOUT = 8 (was 60)
v7 …
```
> HUSBZB-1 config regression fix for Aqara devices
